import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'
import { Resend } from 'resend'
import { generateDepositExcel } from '@/lib/excel-deposit'
import { generateWorkingDaysExcel } from '@/lib/excel-working-days'
import { generateWorkingDaysByClientExcel } from '@/lib/excel-working-days-by-client'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  const cookieStore = await cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll() },
        setAll() {},
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
  }

  const serviceClient = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  const [{ data: profile }, { data: access }] = await Promise.all([
    serviceClient.from('profiles').select('is_admin, display_id, email').eq('id', user.id).single(),
    serviceClient.from('user_apps').select('id, permissions').eq('user_id', user.id).eq('app_slug', 'reports').limit(1),
  ])

  if (!profile?.is_admin && (!access || access.length === 0)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  if (!profile?.email) {
    return NextResponse.json({ error: 'No email present on user setup. Please contact system admin.' }, { status: 400 })
  }

  const recipientEmail = profile.email

  const { reportType, reportData } = await request.json()

  if (!reportType || !reportData) {
    return NextResponse.json({ error: 'reportType and reportData are required.' }, { status: 400 })
  }

  // Check report-level permission
  if (!profile?.is_admin) {
    const perms = access![0].permissions as Record<string, boolean> | null
    if (!perms?.[reportType]) {
      return NextResponse.json({ error: 'You do not have access to this report type.' }, { status: 403 })
    }
  }

  try {
    let buffer: Buffer
    let filename: string
    let subject: string
    const hrCode = reportData.contractor?.HrCode ?? 'unknown'
    const contractorName = reportData.contractor
      ? `${reportData.contractor.FirstName} ${reportData.contractor.LastName}`
      : 'Unknown'
    const date = new Date().toISOString().slice(0, 10)

    if (reportType === 'deposit') {
      buffer = await generateDepositExcel(reportData)
      filename = `Deposit_Report_${hrCode}_${date}.xlsx`
      subject = `Deposit Report — ${hrCode} ${contractorName}`
    } else if (reportType === 'working-days') {
      buffer = await generateWorkingDaysExcel(reportData)
      filename = `Working_Days_${hrCode}_${date}.xlsx`
      subject = `Deposit - Working Day Count — ${hrCode} ${contractorName}`
    } else if (reportType === 'working-days-by-client') {
      buffer = await generateWorkingDaysByClientExcel(reportData)
      const epoch = reportData.targetEpoch
      filename = `Working_Days_by_Client_Wk${epoch?.week ?? 0}_${epoch?.year ?? 0}_${date}.xlsx`
      subject = `Working Days by Client — Week ${epoch?.week ?? 0}, ${epoch?.year ?? 0}`
    } else {
      return NextResponse.json({ error: 'Unknown report type.' }, { status: 400 })
    }

    const { error: sendError } = await resend.emails.send({
      from: process.env.NOTIFY_FROM_EMAIL!,
      to: recipientEmail,
      subject,
      html: reportType === 'working-days-by-client'
        ? `<p>Please find attached the Working Days by Client report for Week ${reportData.targetEpoch?.week ?? 0}, ${reportData.targetEpoch?.year ?? 0}.</p><p>Generated by ${profile?.display_id ?? 'GS Apps'} on ${new Date().toLocaleDateString('en-GB')}.</p>`
        : `<p>Please find attached the ${reportType === 'deposit' ? 'Deposit Report' : 'Deposit - Working Day Count Report'} for <strong>${hrCode} — ${contractorName}</strong>.</p><p>Generated by ${profile?.display_id ?? 'GS Apps'} on ${new Date().toLocaleDateString('en-GB')}.</p>`,
      attachments: [
        {
          filename,
          content: buffer.toString('base64'),
        },
      ],
    })

    if (sendError) {
      console.error('Email send error:', sendError)
      return NextResponse.json({ error: 'Failed to send email.' }, { status: 500 })
    }

    return NextResponse.json({ ok: true })
  } catch (err) {
    console.error('Email report error:', err)
    return NextResponse.json({ error: 'Failed to generate and send report.' }, { status: 500 })
  }
}
